In [3]:
from sklearn import svm, datasets 
iris = datasets.load_iris() 

In [4]:
dir(iris) 

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [5]:
import pandas as pd 

In [6]:
df = pd.DataFrame(iris.data, columns=iris.feature_names) 
df 

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [7]:
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x]) 

In [8]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  flower
0                5.1               3.5                1.4               0.2  setosa
1                4.9               3.0                1.4               0.2  setosa
2                4.7               3.2                1.3               0.2  setosa
3                4.6               3.1                1.5               0.2  setosa
4                5.0               3.6                1.4               0.2  setosa

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)

In [10]:
model = svm.SVC(kernel='rbf', C=30, gamma='auto') 
model.fit(X_train, y_train) 
model.score(X_test, y_test) 

1.0

### K Fold for cross validation

In [11]:
from sklearn.model_selection import cross_val_score 

In [12]:
cross_val_score(svm.SVC(kernel='linear', C=10, gamma='auto'), iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [13]:
cross_val_score(svm.SVC(kernel='rbf', C=10, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [14]:
cross_val_score(svm.SVC(kernel='rbf', C=20, gamma='auto'), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [15]:
import numpy as np 
kernels = ['rbf', 'linear']
C = [1,10,20] 
avg_scores = {} 
for kval in kernels: 
    for cval in C: 
        cv_scores = cross_val_score(svm.SVC(kernel=kval, C=cval, gamma='auto'), iris.data, iris.target, cv=5)
        avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)
avg_scores

{'rbf_1': np.float64(0.9800000000000001),
 'rbf_10': np.float64(0.9800000000000001),
 'rbf_20': np.float64(0.9666666666666668),
 'linear_1': np.float64(0.9800000000000001),
 'linear_10': np.float64(0.9733333333333334),
 'linear_20': np.float64(0.9666666666666666)}

### GridSearchCV for hyperparameter tuning

In [16]:
from sklearn.model_selection import GridSearchCV 

clf = GridSearchCV(svm.SVC(), {
    'C': [1,10,20], 
    'kernel': ['rbf', 'linear']
}, cv=5, return_train_score=False) 

clf.fit(iris.data, iris.target) 
clf.cv_results_

{'mean_fit_time': array([0.00110784, 0.00099797, 0.00059776, 0.00019989, 0.00039878,
        0.00200243]),
 'std_fit_time': array([2.16301061e-04, 3.02481680e-06, 4.88145686e-04, 3.99780273e-04,
        7.97557831e-04, 1.36606980e-05]),
 'mean_score_time': array([0.00029712, 0.        , 0.00041389, 0.00101953, 0.00148306,
        0.00099707]),
 'std_score_time': array([3.97600719e-04, 0.00000000e+00, 5.07532981e-04, 7.33989166e-05,
        6.55456160e-04, 8.02730961e-06]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
 

In [17]:
df = pd.DataFrame(clf.cv_results_)
df 

mean_fit_time  std_fit_time  mean_score_time  ...  mean_test_score  std_test_score rank_test_score
0       0.001108      0.000216         0.000297  ...         0.966667        0.021082               5
1       0.000998      0.000003         0.000000  ...         0.980000        0.016330               1
2       0.000598      0.000488         0.000414  ...         0.980000        0.016330               1
3       0.000200      0.000400         0.001020  ...         0.973333        0.038873               4
4       0.000399      0.000798         0.001483  ...         0.980000        0.016330               1
5       0.002002      0.000014         0.000997  ...         0.966667        0.042164               5

[6 rows x 15 columns]

In [18]:
dir(clf)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_routed_params_for_fit',
 '_get_scorers',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_run_sea

In [19]:
clf.best_score_

np.float64(0.9800000000000001)

In [20]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

### RandomizeSearchCV 

In [21]:
from sklearn.model_selection import RandomizedSearchCV 
rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {
        'C': [1,10,20],
        'kernel': ['rbf', 'linear']
    }, 
    cv=5, 
    return_train_score=False, 
    n_iter=2
)

rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0        1          rbf             0.98
1       10          rbf             0.98

### Choosing a best model 

In [22]:
from sklearn import svm 
from sklearn.ensemble import RandomForestClassifier 
from sklearn.linear_model import LogisticRegression 

In [23]:
model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'), 
        'params': {
            'C': [1,10,20], 
            'kernel': ['rbf', 'linear']
        }
    }, 
    'random_forest': {
        'model': RandomForestClassifier(), 
        'params': {
            'n_estimators': [1,5,10]
        }
    }, 
    'logistic_regression': {
        'model': LogisticRegression(solver='liblinear', multi_class='auto'), 
        'params': {
            'C': [1,5,10]
        }
    }
}

In [25]:
scores = [] 

for model_name, mp in model_params.items(): 
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target) 
    scores.append({
        'model': model_name, 
        'best_score': clf.best_score_, 
        'best_params': clf.best_params_
    })

C:\Users\madhu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\madhu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\madhu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in versio

In [26]:
scores 

[{'model': 'svm',
  'best_score': np.float64(0.9800000000000001),
  'best_params': {'C': 1, 'kernel': 'rbf'}},
 {'model': 'random_forest',
  'best_score': np.float64(0.9533333333333334),
  'best_params': {'n_estimators': 5}},
 {'model': 'logistic_regression',
  'best_score': np.float64(0.9666666666666668),
  'best_params': {'C': 5}}]

In [31]:
df = pd.DataFrame(scores)
df 

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.953333        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}