In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC 
from sklearn.ensemble import RandomForestClassifier
import numpy as np 
from sklearn.datasets import load_digits 

digits = load_digits()

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [20]:
lr = LogisticRegression() 
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

C:\Users\madhu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [21]:
svm = SVC() 
svm.fit(X_train, y_train)
svm.score(X_test, y_test) 

0.9907407407407407

In [22]:
rf = RandomForestClassifier() 
rf.fit(X_train, y_train) 
rf.score(X_test, y_test) 

0.9777777777777777

In [23]:
from sklearn.model_selection import KFold 
kf = KFold(n_splits=3, random_state=None, shuffle=False) 

In [25]:
for train_index, test_index in kf.split([1,2,3,4,5,6,8,9]):
    print(train_index, test_index)
    

[3 4 5 6 7] [0 1 2]
[0 1 2 6 7] [3 4 5]
[0 1 2 3 4 5] [6 7]


In [26]:
def get_score(model, X_train, X_test, y_train, y_test): 
    model.fit(X_train, y_train) 
    return model.score(X_test, y_test) 

In [27]:
get_score(lr, X_train, X_test, y_train, y_test)

C:\Users\madhu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [28]:
# divide each of the classification categories in a uniform way 
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3) 

In [36]:
scores_lr = []
scores_svm = []
scores_rf = [] 

for train_index, test_index in kf.split(digits.data): 
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_lr.append(get_score(lr, X_train, X_test, y_train, y_test)) 
    scores_svm.append(get_score(svm, X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

C:\Users\madhu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\madhu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stab

In [37]:
scores_lr 

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [38]:
scores_rf

[0.9332220367278798, 0.9515859766277128, 0.9265442404006677]

In [39]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [40]:
from sklearn.model_selection import cross_val_score 

In [41]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

C:\Users\madhu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\madhu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stab

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [42]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [44]:
cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target)

array([0.92777778, 0.90555556, 0.95264624, 0.95821727, 0.92200557])